config/routes.rb
Rails.application.routes.draw do
  resources :ascetic_plans
  resources :ascetic_practices
  root to: 'main#home'
  get '/details/:date', to: 'main#details'
  post '/reading/:date', to: 'main#update_reading'
  post '/update_ascetic_plans', to: 'main#update_ascetic_plans'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ascetic_plan.rb
class AsceticPlan < ApplicationRecord
  belongs_to :ascetic_practice
end

app/models/ascetic_practice.rb
class AsceticPractice < ApplicationRecord
  has_many :ascetic_plans
end

app/models/reading.rb
class Reading < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ascetic_plans_controller.rb
class AsceticPlansController < ApplicationController
  before_action :set_ascetic_plan, only: [:show, :edit, :update, :destroy]

  # GET /ascetic_plans
  # GET /ascetic_plans.json
  def index
    @ascetic_plans = AsceticPlan.all
  end

  # GET /ascetic_plans/1
  # GET /ascetic_plans/1.json
  def show
  end

  # GET /ascetic_plans/new
  def new
    @ascetic_plan = AsceticPlan.new
  end

  # GET /ascetic_plans/1/edit
  def edit
  end

  # POST /ascetic_plans
  # POST /ascetic_plans.json
  def create
    @ascetic_plan = AsceticPlan.new(ascetic_plan_params)

    respond_to do |format|
      if @ascetic_plan.save
        format.html { redirect_to @ascetic_plan, notice: 'Ascetic plan was successfully created.' }
        format.json { render :show, status: :created, location: @ascetic_plan }
      else
        format.html { render :new }
        format.json { render json: @ascetic_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ascetic_plans/1
  # PATCH/PUT /ascetic_plans/1.json
  def update
    respond_to do |format|
      if @ascetic_plan.update(ascetic_plan_params)
        format.html { redirect_to @ascetic_plan, notice: 'Ascetic plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @ascetic_plan }
      else
        format.html { render :edit }
        format.json { render json: @ascetic_plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ascetic_plans/1
  # DELETE /ascetic_plans/1.json
  def destroy
    @ascetic_plan.destroy
    respond_to do |format|
      format.html { redirect_to ascetic_plans_url, notice: 'Ascetic plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ascetic_plan
      @ascetic_plan = AsceticPlan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ascetic_plan_params
      params.require(:ascetic_plan).permit(:ascetic_practice_id, :date)
    end
end

app/controllers/ascetic_practices_controller.rb
class AsceticPracticesController < ApplicationController
  before_action :set_ascetic_practice, only: [:show, :edit, :update, :destroy]

  # GET /ascetic_practices
  # GET /ascetic_practices.json
  def index
    @ascetic_practices = AsceticPractice.all
  end

  # GET /ascetic_practices/1
  # GET /ascetic_practices/1.json
  def show
  end

  # GET /ascetic_practices/new
  def new
    @ascetic_practice = AsceticPractice.new
  end

  # GET /ascetic_practices/1/edit
  def edit
  end

  # POST /ascetic_practices
  # POST /ascetic_practices.json
  def create
    @ascetic_practice = AsceticPractice.new(ascetic_practice_params)

    respond_to do |format|
      if @ascetic_practice.save
        format.html { redirect_to @ascetic_practice, notice: 'Ascetic practice was successfully created.' }
        format.json { render :show, status: :created, location: @ascetic_practice }
      else
        format.html { render :new }
        format.json { render json: @ascetic_practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ascetic_practices/1
  # PATCH/PUT /ascetic_practices/1.json
  def update
    respond_to do |format|
      if @ascetic_practice.update(ascetic_practice_params)
        format.html { redirect_to @ascetic_practice, notice: 'Ascetic practice was successfully updated.' }
        format.json { render :show, status: :ok, location: @ascetic_practice }
      else
        format.html { render :edit }
        format.json { render json: @ascetic_practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ascetic_practices/1
  # DELETE /ascetic_practices/1.json
  def destroy
    @ascetic_practice.destroy
    respond_to do |format|
      format.html { redirect_to ascetic_practices_url, notice: 'Ascetic practice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ascetic_practice
      @ascetic_practice = AsceticPractice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ascetic_practice_params
      params.require(:ascetic_practice).permit(:description)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def home
    today = Date.today
    today_details = day_details(today)
    week = today.beginning_of_week
    @tabs = {
      today: {
        label: 'Today',
        component: 'Today',
      },
      week: {
        label: 'This week',
        component: 'Week',
        props: {
          days: days_for(week),
          week: week
        }
      },
      edit: {
        label: 'Edit content',
        component: 'Edit',
        props: {
          today: today,
          details: today_details,
          ascetic_practices: AsceticPractice.all.to_a,
        }
      },
    }
  end

  # all the info for a particular date, in json form
  def details
    current = Date.parse(params[:date])
    return render json: day_details(current)
  end

  def update_reading
    date = Date.parse(params[:date])
    reading = Reading.where(date: date).first_or_create
    reading.update(text: params[:text])
    return render json: {status: :ok}
  end

  def update_ascetic_plans
    AsceticPlan.where(date: params[:date]).destroy_all
    if params[:ids]
      params[:ids].each do |id|
        AsceticPlan.create(ascetic_practice_id: id, date: params[:date])
      end
    end
  end

  private

    def days_for(week_start)
      results = []
      7.times do |i|
        current = week_start + i
        results.push(day_details(current))
      end
      results
    end

    def day_details(date)
      reading = Reading.where(date: date).first
      asceticisms = AsceticPlan.where(date: date).map do |ap|
        ap.ascetic_practice.description
      end
      {
        date: date,
        reading: reading && reading.text,
        practices: asceticisms,
        practice_ids: AsceticPlan.where(date: date).map(&:ascetic_practice_id).uniq,
      }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ascetic_plans_helper.rb
module AsceticPlansHelper
end

app/helpers/ascetic_practices_helper.rb
module AsceticPracticesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/ascetic_plans/_form.html.erb
<%= form_with(model: ascetic_plan, local: true) do |form| %>
  <% if ascetic_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ascetic_plan.errors.count, "error") %> prohibited this ascetic_plan from being saved:</h2>

      <ul>
      <% ascetic_plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ascetic_practice_id %>
    <%= form.number_field :ascetic_practice_id %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ascetic_plans/edit.html.erb
<h1>Editing Ascetic Plan</h1>

<%= render 'form', ascetic_plan: @ascetic_plan %>

<%= link_to 'Show', @ascetic_plan %> |
<%= link_to 'Back', ascetic_plans_path %>

app/views/ascetic_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ascetic Plans</h1>

<table>
  <thead>
    <tr>
      <th>Ascetic practice</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ascetic_plans.each do |ascetic_plan| %>
      <tr>
        <td><%= ascetic_plan.ascetic_practice_id %></td>
        <td><%= ascetic_plan.date %></td>
        <td><%= link_to 'Show', ascetic_plan %></td>
        <td><%= link_to 'Edit', edit_ascetic_plan_path(ascetic_plan) %></td>
        <td><%= link_to 'Destroy', ascetic_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ascetic Plan', new_ascetic_plan_path %>

app/views/ascetic_plans/new.html.erb
<h1>New Ascetic Plan</h1>

<%= render 'form', ascetic_plan: @ascetic_plan %>

<%= link_to 'Back', ascetic_plans_path %>

app/views/ascetic_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ascetic practice:</strong>
  <%= @ascetic_plan.ascetic_practice_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @ascetic_plan.date %>
</p>

<%= link_to 'Edit', edit_ascetic_plan_path(@ascetic_plan) %> |
<%= link_to 'Back', ascetic_plans_path %>

app/views/ascetic_practices/_form.html.erb
<%= form_with(model: ascetic_practice, local: true) do |form| %>
  <% if ascetic_practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ascetic_practice.errors.count, "error") %> prohibited this ascetic_practice from being saved:</h2>

      <ul>
      <% ascetic_practice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ascetic_practices/edit.html.erb
<h1>Editing Ascetic Practice</h1>

<%= render 'form', ascetic_practice: @ascetic_practice %>

<%= link_to 'Show', @ascetic_practice %> |
<%= link_to 'Back', ascetic_practices_path %>

app/views/ascetic_practices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ascetic Practices</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ascetic_practices.each do |ascetic_practice| %>
      <tr>
        <td><%= ascetic_practice.description %></td>
        <td><%= link_to 'Show', ascetic_practice %></td>
        <td><%= link_to 'Edit', edit_ascetic_practice_path(ascetic_practice) %></td>
        <td><%= link_to 'Destroy', ascetic_practice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ascetic Practice', new_ascetic_practice_path %>

app/views/ascetic_practices/new.html.erb
<h1>New Ascetic Practice</h1>

<%= render 'form', ascetic_practice: @ascetic_practice %>

<%= link_to 'Back', ascetic_practices_path %>

app/views/ascetic_practices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @ascetic_practice.description %>
</p>

<%= link_to 'Edit', edit_ascetic_practice_path(@ascetic_practice) %> |
<%= link_to 'Back', ascetic_practices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exodus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/home.html.erb
<div class="page-container">
  <h1>Permanent rules</h1>
  <ol>
    <li>No man left behind: If someone commits a mortal sin, he tells the group, and for the next 24 hours, we will fast.</li>
    <li>11am sunday morning meetings at the cathedral gym</li>
    <li>daily anchor checkins</li>
    <li>Daily 20min of prayer</li>
  </ol>
  <hr/>
  <%= react_component('Tabs', tabs: @tabs) %>
</div>